In [1]:
import numpy as np
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [2]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [5]:
b=np.ones(4)
print(a)
print(b)
print(a-b)

[1 2 3 4]
[1. 1. 1. 1.]
[0. 1. 2. 3.]


In [10]:
a*b

array([2., 4., 6., 8.])

In [12]:
c=np.diag([1,2,3,4])
print(c*c)
print("********************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
********************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [14]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
a==b

array([ True,  True,  True,  True])

In [15]:
a>b

array([False, False, False, False])

In [21]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])
np.array_equal(c,a)

True

In [22]:
np.array_equal(a,b)

False

In [26]:
a=np.array([1,0,1,0],dtype=bool)
b=np.array([1,1,0,0],dtype=bool)

np.logical_or(a,b)

array([ True,  True,  True, False])

In [27]:
np.logical_and(a,b)

array([ True, False, False, False])

In [28]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [29]:
np.log(a)

C:\Users\ADMIN\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [30]:
np.exp(a)     #e^x

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [31]:
#shape Mismatch

In [32]:
a=np.arange(5)

np.sum(a)

10

In [33]:
a=np.array([[1,1],[2,2]])
a

array([[1, 1],
       [2, 2]])

In [35]:
a.sum(axis=0)

array([3, 3])

In [36]:
a.sum(axis=1)

array([2, 4])

In [37]:
a=np.arange(5)

np.min(a)

0

In [39]:
a.argmin()  #index where value is min

0

In [40]:
np.max(a)

4

In [41]:
np.argmax(a)#index where value is max

4

In [43]:
np.all([True,True,False])

False

In [44]:
np.any([True,True,False])

True

In [45]:
a=np.zeros((50,50))
np.any(a!=0)

False

In [46]:
np.all(a==a)

True

In [47]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([6,4,3,4])

((a<=b)&(b<=c)).all()

False

In [48]:
a=np.array([1,2,3,4])
a.mean()

2.5

In [54]:
b=np.array([[5,2,2,4],[5,6,7,9]])
np.median(b,axis=-1)

array([3. , 6.5])

In [55]:
np.median(b,axis=1)

array([3. , 6.5])

In [56]:
a.std() #standard deviation

1.118033988749895

In [60]:
data=np.loadtxt('ex.txt')

In [61]:
data

array([[ 1., 12.],
       [ 2., 13.],
       [ 3., 34.],
       [ 4., 45.]])

In [62]:
#transpose
s_no,pop=data.T
print(s_no)

[1. 2. 3. 4.]


In [63]:
 #broadcasting

In [69]:
a=np.tile(np.arange(0,40,10),(3,1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [70]:
a=a.T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [71]:
b=np.array([0,1,2])

In [72]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [75]:
a=np.arange(0,40,10)
print(a.shape)
a=a[:,np.newaxis]   ## adds a new axis ->  2D array
a.shape

(4,)


(4, 1)

In [76]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [77]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [79]:
#flattning



a=np.array([[1,2,3],[4,5,6]])

In [87]:
b=a.ravel().copy()

In [88]:
b

array([1, 2, 3, 4, 5, 6])

In [89]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [90]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [91]:
#reshaping

print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [92]:
b=a.ravel()
print(b)

[1 2 3 4 5 6]


In [94]:
b.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
b[0,0]=100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [96]:
a=np.arange(4*3*2).reshape(4,3,2)
a.shape

(4, 3, 2)

In [97]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [98]:
a[0,2,1]

5

In [100]:
a=np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [101]:
b=a
a.resize((6,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [102]:
a=np.array([[5,4,6],[3,2,3]])
b=np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 3, 3]])

In [104]:
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 3, 3]])

In [105]:
a=np.array([4,3,1,2])
j=np.argsort(a)
j


array([2, 3, 1, 0], dtype=int64)

In [106]:
a[j]

array([1, 2, 3, 4])