In [3]:
import numpy as np
a = np.array([0,2,3,4])
print(a)
print(np.arange(10))

[0 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
L=range(1000)
%timeit [i**2 for i in L]

842 µs ± 22 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
a=np.arange(1000)
%timeit a**2

3.37 µs ± 23.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
a.ndim
#dimension of array

1

In [7]:
b=np.array([[0,4,3],[7,8,9]])

In [8]:
b.shape

(2, 3)

In [9]:
b.ndim

2

In [10]:
len(b)

2

In [11]:
#3d array

In [12]:
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

In [13]:
c.ndim

3

In [14]:
b=np.arange(1,10,2)
print(b)

[1 3 5 7 9]


In [15]:
a=np.linspace(0,1,6)
a
#(start,end,no. of points including start and end)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [16]:
z=np.ones((3,3))
z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
z=np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.eye(3)#diagonal matrices

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [20]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
np.diag(z)

array([0., 0., 0.])

In [22]:
a=np.random.rand(4)
a

array([0.01314069, 0.92406983, 0.27702269, 0.64692989])

In [23]:
a=np.random.randn(4)
a

array([-0.84937747,  1.13886778, -0.460091  , -0.23439141])

In [24]:
a=np.arange(10)
a.dtype

dtype('int32')

In [25]:
a=np.arange(10,dtype='float64')

In [26]:
a.dtype

dtype('float64')

In [27]:
d=np.array([1+2j,2+4j])
print(d.dtype)

complex128


In [28]:
# same we can  create array of bool and string

In [29]:
#slicing(subarray find)

In [30]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a[1:8:2] #[startindex:endindex(exclusive):step]

array([1, 3, 5, 7])

In [32]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [33]:
b=np.arange(5)
a[5:]=b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [34]:
b=a[::2]
b

array([0, 2, 4, 3, 1])

In [35]:
np.shares_memory(a,b)

True

In [36]:
b[0]=10
b[1]=999
a

array([ 10,   1, 999,   3,   4,   4,   3,   2,   1,   0])

In [37]:
b

array([ 10, 999,   4,   3,   1])

In [38]:
b=np.arange(5)
a[5:]=b[::-1].copy()
a

array([ 10,   1, 999,   3,   4,   4,   3,   2,   1,   0])

In [39]:
np.shares_memory(a,b)

False

In [40]:
a=np.random.randint(0,20,15)
a

array([ 9,  7, 19,  2, 14,  3,  0,  1, 13,  5,  0,  9, 19, 11,  1])

In [41]:
mask = (a%2==0)

In [47]:
new_a=a[mask]
print(new_a)
print(a)
print(np.count_nonzero(new_a))

[ 2 14  0  0]
[ 9  7 19  2 14  3  0  1 13  5  0  9 19 11  1]
2


In [61]:
m= (a%2==1)
a[m]=-3
a

array([-3, 14, -3,  2, 14, -3, 18, -3,  8,  0, -3, -3, -3, -3, 18])

In [62]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [64]:
a[[9,7]]=-200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

AttributeError: 'numpy.ndarray' object has no attribute 'count'